#!/usr/bin/env bash

set -euo pipefail

platex -shell-escape -synctex=1 "$1"

# if exist .bib file, run biber
set +e
ls *.bib >/dev/null 2>&1
BIB_EXIST=$?
set -e

if [ $? -eq 0 ];
then
  biber --bblencoding=utf8 -u -U --output_safechars $(basename $1 .tex)
fi

platex -shell-escape -synctex=1 "$1"

# make pdf
dvipdfmx "`basename "$1" .tex`"
